source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

#基础框架
target 'WZKLibrary' do
  pod 'JKCategories'#扩展类
  pod 'MBProgressHUD' #HUD
  pod 'LEEAlert', '1.2.1' #Alert弹框
  pod 'SAMKeychain' #钥匙串

  pod 'WMPageController', '2.3.0' #pageViewController,测划翻页。
  pod 'Masonry'#layout布局
  pod 'WebViewJavascriptBridge', '~> 6.0' #H5对接js框架

end
